[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "eaia"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "langgraph>=1.0.0,<2.0.0",
    "langgraph-checkpoint",
    "langchain>=1.0.0,<2.0.0",
    "deepagents==0.1.2",
    "langchain-auth",
    "langchain-openai>=1.0.0,<2.0.0",
    "langchain-anthropic>=1.0.0,<2.0.0",
    "langgraph-prebuilt>=1,<2",
    "langchain-core>=1.0.0,<2.0.0",
    "google-api-python-client>=2.128.0,<3.0.0",
    "google-auth-oauthlib>=1.2.0,<2.0.0",
    "google-auth-httplib2>=0.2.0,<0.3.0",
    "langgraph-sdk",
    "langsmith",
    "arcadepy",
    "PyJWT",
    "pytz",
    "pyyaml",
    "python-dateutil>=2.9.0.post0,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "langmem==0.0.5rc6",
    "slack_sdk",
    "aiohttp",
    "langgraph-api>=0.5,<0.6",
    "langgraph-cli>=0.4.7,<0.5.0",
    "ai-filesystem>=0.1.4,<0.2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv]
default-groups = ["dev"]

[dependency-groups]
dev = [
    "ipykernel>=6.29.4,<7.0.0",
    "pytest-asyncio>=0.23.6,<0.24.0",
    "pytest>=8.2.0,<9.0.0",
    "pytest-watch>=4.2.0,<5.0.0",
    "vcrpy>=6.0.1,<7.0.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
