[tool.poetry]
name = "eaia"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
deepagents = "0.0.11rc1"
langgraph = "*"
langgraph-checkpoint = "*"
langchain = "^1.0.0a10"
langchain-auth = "*"
langchain-openai = "^1.0.0a2"
langchain-anthropic = "^1.0.0a2"
google-api-python-client = "^2.128.0"
google-auth-oauthlib = "^1.2.0"
google-auth-httplib2 = "^0.2.0"
langgraph-sdk = "*"
langsmith = "*"
arcadepy = "*"
PyJWT = "*"
pytz = "*"
pyyaml = "*"
python-dateutil = "^2.9.0.post0"
python-dotenv = "^1.0.1"
langmem = "0.0.5rc6"
slack_sdk = "*"
aiohttp = "*"
langgraph-api = "^0.4.31"
langgraph-cli = "^0.4.2"
ai-filesystem = "^0.1.4"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
customer_support = ["*.txt", "*.rst"]

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
pytest-asyncio = "^0.23.6"
pytest = "^8.2.0"
pytest-watch = "^4.2.0"
vcrpy = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"
